version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 1.18-bullseye

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - mysql
      - postgresql

    environment:
      PG_HOST: postgresql
      PG_USER: postgres
      PG_DATABASE: dinotest
      PG_PASSWORD: mysecretpassword
      MYSQL_DATABASE: dinotest
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysecretpassword

  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dinotest
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_ROOT_HOST: '%'

  postgresql:
    image: "postgres:13"
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: dinotest
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
