name: bintray

on:
  push:
    branches:
    - master

jobs:

  macos:
    name: release --platforms darwin
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
    - uses: jfrog/setup-jfrog-cli@v1
    - id: gobuild
      run: go run scripts/build/main.go
    - run: echo ${{steps.gobuild.outputs.version}}
    - run: zip -X -j sqlc-devel-darwin-amd64.zip ./sqlc
    - run: tar -zcvf sqlc-devel-darwin-amd64.tar.gz ./sqlc
    - run: jfrog bt upload --user kyleconroy --key "$BINTRAY_API_KEY" --publish --override "sqlc-devel-darwin-amd64.*" sqlc/devel/sqlc/${{steps.gobuild.outputs.version}} ${{steps.gobuild.outputs.version}}/

      env:
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

  linux:
    name: release --platforms linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
    - uses: jfrog/setup-jfrog-cli@v1
    - id: gobuild
      run: go run scripts/build/main.go
    - run: echo ${{steps.gobuild.outputs.version}}
    - run: zip -X -j sqlc-devel-linux-amd64.zip ./sqlc
    - run: tar -zcvf sqlc-devel-linux-amd64.tar.gz ./sqlc
    - run: jfrog bt upload --user kyleconroy --key "$BINTRAY_API_KEY" --publish --override "sqlc-devel-linux-amd64.*" sqlc/devel/sqlc/${{steps.gobuild.outputs.version}} ${{steps.gobuild.outputs.version}}/
      env:
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
