name: go
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  windows-build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: go build ./...

  darwin-build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: go build ./...

  build:
    name: test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: mysecretpassword
          MYSQL_DATABASE: mysql
        ports:
        - 3306:3306

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: gotestsum
      run: go install gotest.tools/gotestsum@latest

    - name: install ./...
      run: go install ./...

    - name: test ./...
      run: gotestsum --junitfile junit.xml -- --tags=examples ./...
      env:
        PG_USER: postgres
        PG_HOST: localhost
        PG_DATABASE: postgres
        PG_PASSWORD: postgres
        PG_PORT: ${{ job.services.postgres.ports['5432'] }}
        MYSQL_DATABASE: mysql
        MYSQL_HOST: localhost
        MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
        MYSQL_ROOT_PASSWORD: mysecretpassword

    - name: build internal/endtoend
      run: go build ./...
      working-directory: internal/endtoend/testdata

    - name: report
      if: ${{ github.ref == 'refs/heads/main' }}
      run: ./scripts/report.sh
      env:
        BUILDKITE_ANALYTICS_TOKEN: ${{ secrets.BUILDKITE_ANALYTICS_TOKEN }}
