name: equinox

on:
  push:
    branches:
    - master

jobs:

  windows:
    name: release --platforms windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: equinox-io/setup-release-tool@v1.1.0
    - name: equinox release
      env:
        EQUINOX_API_TOKEN: ${{ secrets.EQUINOX_API_TOKEN }}
        EQUINOX_SIGNING_KEY: ${{ secrets.EQUINOX_SIGNING_KEY }}
      run: go run scripts/release.go -draft windows_amd64

  macos:
    name: release --platforms darwin
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: equinox-io/setup-release-tool@v1.1.0
    - name: equinox release
      env:
        EQUINOX_API_TOKEN: ${{ secrets.EQUINOX_API_TOKEN }}
        EQUINOX_SIGNING_KEY: ${{ secrets.EQUINOX_SIGNING_KEY }}
      run: go run scripts/release.go -draft darwin_amd64

  linux:
    name: release --platforms linux
    runs-on: ubuntu-latest
    needs: [macos, windows]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: equinox-io/setup-release-tool@v1.1.0
    - name: equinox release
      env:
        EQUINOX_API_TOKEN: ${{ secrets.EQUINOX_API_TOKEN }}
        EQUINOX_SIGNING_KEY: ${{ secrets.EQUINOX_SIGNING_KEY }}
      run: go run scripts/release.go linux_amd64


