name: equinox

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:

  macos:
    name: release --platforms darwin
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - run: brew install eqnxio/equinox/release-tool
    - name: equinox release
      env:
        EQUINOX_API_TOKEN: ${{ secrets.EQUINOX_API_TOKEN }}
        EQUINOX_SIGNING_KEY: ${{ secrets.EQUINOX_SIGNING_KEY }}
      run: go run scripts/release.go -draft darwin_amd64

  linux:
    name: release --platforms linux
    runs-on: ubuntu-latest
    needs: [macos]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - run: curl -O https://bin.equinox.io/c/mBWdkfai63v/release-tool-stable-linux-amd64.tgz
    - run: tar -xzvf release-tool-stable-linux-amd64.tgz
    - name: equinox release
      env:
        EQUINOX_API_TOKEN: ${{ secrets.EQUINOX_API_TOKEN }}
        EQUINOX_SIGNING_KEY: ${{ secrets.EQUINOX_SIGNING_KEY }}
      run: go run scripts/release.go linux_amd64


