name: sqlc-pg-gen
on:
  workflow_dispatch:
jobs:
  gen:
    name: sqlc-pg-gen
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:15.0-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - run: go build -o sqlc-pg-gen ./internal/tools/sqlc-pg-gen
    - run: mkdir -p gen/contrib
    - run: ./sqlc-pg-gen gen
      env:
        PG_USER: postgres
        PG_HOST: localhost
        PG_DATABASE: postgres
        PG_PASSWORD: postgres
        PG_PORT: ${{ job.services.postgres.ports['5432'] }}
    - name: Save results
      uses: actions/upload-artifact@v3
      with:
        name: sqlc-pg-gen-results
        path: gen

